### ISSUE TITLE
Unable to change starting password due to length

### ISSUE THREAD

**Issue by jelly-payton** [opspotes/jellystat#2]
I got Jellystats setup for the first time recently. When I first set it up I used a 3 character password. I want to do a pw change, using a password 9 characters long and I get "Password Must be at least 6 characters long", see attached screenshot
 
![Screenshot from 2024-10-16 22-12-15](https://github.com/user-attachments/assets/b850009b-c1a2-42c3-82e1-ad25e8b43f4e)

**Comment by LaSylv** [comment]
Will look into it

**Comment by LaSylv** [comment]
I cant find a way to reproduce the bug

Would you have steps so that I can dig into it ?

**Comment by jelly-payton** [comment]
It's just utilizing a docker compose from the example template you have 

```
version: "3"
services:
  jellystat:
    container_name: jellystat
    image: ghcr.io/jellystat:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: jfstat
      JWT_SECRET: "my-secret-jwt-key"
    depends_on:
      - jellystat-db
    ports:
      - "3000:3000"

  jellystat-db:
    container_name: jellystat-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "jfstat"
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
```


New instance is made, account setup process and only enter 3 characters as password then try to change your password and you get will the error noted. 

I assume you have a check on the Password Change page on the Current Password input box for pw length. While there is no check on the account creation thus allowing a password less than 6.

Just tried it again in a new container and was able to repeat it
